### ISSUE TITLE
Multiple fields for ordering by when using previous, next

### ISSUE THREAD

**Issue by pnomolos** [radar/by_star#48] opened 2015-02-20 19:30 UTC
Right now you can only set a single field for ordering by when using previous and next.  Most of the time this isn't an issue, but I've run into an issue where things are breaking down for me.

Here's the code for `previous` for reference:

``` ruby
    def previous(options={})
      field = self.class.by_star_start_field
      value = self.send(field.split(".").last)
      self.class.by_star_scope(options.merge(scope_args: self)).where("#{field} < ?", value).reorder("#{field} DESC").first
    end
```

Part of my issue is the use of `where("#{field} < ?", value)` rather than something like `where("#{field} <= ? AND id != ?", value, self.id)` because my field is month-based (and can't be changed) and on very rare occasions I have two values with the same month, so `previous`/`next` will always skip to a different month.  I do realize that my proposed fix is over-simplified and falls apart when dealing with legacy schemas, composite PKs, etc, but it's for the sake of example.

Following up from that is then the inability to order records by some criteria within the same month, should the previous issue be fixable.

I don't know if this is something that you want to deal with, or if it's too niche to be a problem.  I'm more than willing to create a full pull request should you be OK with trying to solve it, and would welcome any suggestions, criticism, or thoughts.

Thanks!

**Comment by johnnyshields** [comment] 2015-02-20 21:14
I don't understand what you mean by "month based". How is your data stored in the DB? As a string? YYYY-MM ?

**Comment by pnomolos** [comment] 2015-02-20 21:15
As a Postgres date field, with the day always set to the 1st.

**Comment by johnnyshields** [comment] 2015-02-20 21:31
And so the problem is that since two dates are identical values, it considers them as one?

You fix may not work by the way (i.e. excluding the id), since it can lead to toggling between records A and B in the same month and you can never progress forward.

The best solution I can think of is to slightly randomize the time of the month data in your DB, so that the values are very slightly different (i.e. by a few seconds) and the function will behave consistently.

The only other way would be if Postgres has some native query method that can jump to a given ID in a SELECT statement then get the next record, I don't know if this is supported however.

**Comment by pnomolos** [comment] 2015-02-20 22:02
This is why my proposed solution would allow you to order via multiple fields, my data doesn't even include a timestamp on the date field so adding random seconds would require reworking a bunch of code (as a lot of comparsion checks based on the date could be affected).  My idea was something like the following for the previous method:

```ruby
def previous(options={})
    fields = [*self.class.by_star_start_fields]
    query = self.class.by_star_scope(options.merge(scope_args: self))
    fields.each do |field|
        query = query.where("#{field} <= ?", self.send(field.split(".").last))
    end
    query = query.where("id != ?", self.id).reorder("#{fields.join('DESC, ')} DESC").first
end
```

**Comment by radar** [comment] 2015-02-20 22:39
Perhaps you could define a different `previous` / `next` method that worked based solely on the `id` column. Would that work?

**Comment by pnomolos** [comment] 2015-02-20 22:40
@radar Unfortunately not.  IDs are UUIDs so they aren't orderable.

**Comment by johnnyshields** [comment] 2015-02-21 07:30
Suppose I have the following data

| record | id | date |
| a | 1 |  2015-01-01 |
| b | 2 |  2015-01-01 |
| c | 3 |  2015-01-02 |

`records.where("date <= ?", a.date).where("id != ?", a.id).reorder("date ASC")`

This will return:

| b | 2 |  2015-01-01 |
| c | 3 |  2015-01-02 |

The first being `b`.

Then I do:

`records.where("date <= ?", b.date).where("id != ?", b.id).reorder("date ASC")`

This will return:

| a | 1 |  2015-01-01 |
| c | 3 |  2015-01-02 |

The first being `a`. So we have an infinite loop between `a` and `b`.

**Comment by johnnyshields** [comment] 2015-02-21 07:34
One alternative would be to make `previous_batch` and `next_batch` (or something like that) methods which remove the `.first` specifier hence can return more than one result. I think that might be the best in this case.

**Comment by pnomolos** [comment] 2015-02-21 07:35
This is why I was suggesting being able to order by multiple fields, so you wouldn't end up in an infinite loop

**Comment by johnnyshields** [comment] 2015-02-21 07:46
@pnomolos I don't think that would make a difference. Please try it yourself and see what happens.

**Comment by pnomolos** [comment] 2015-02-23 06:45
@johnnyshields I'll try this out sometime this week, just haven't had time due to some deadlines.

**Comment by johnnyshields** [comment] 2016-05-08 18:16
I thought a bit about this. I think what you need to do is an OR query:

```
where("date = ?", x.date).where("#{field} > ?", x.send(:field))
OR 
where("date <= ?", x.date).where("id != ?", x.id).reorder("date ASC")
```

In general ID is a safe to use here, because UUIDs ARE orderable and guaranteed to be present (the existing logic already uses ID). But we could also give the option for `tiebreaker_field` and `tiebreaker_sort` or something.

**Comment by johnnyshields** [comment] 2019-06-12 11:21
closing as this is out-of-scope for this gem

**Closed by johnnyshields** 2019-06-12 11:21 UTC
